import { siteContentDefaults } from '@/lib/site-content-defaults';

export const portfolioData = {
  siteContent: siteContentDefaults,
  profile: {
    name: 'Akbar Nur Hidayanto',
    monogram: 'ANH',
    eyebrow: 'Discipline turns plans into progress',
    tagline: 'A Journey of Work, Learning & Creation.',
    introduction:
      'Profesional multidisiplin yang bersemangat memecahkan masalah nyata melalui teknologi, pemikiran terstruktur, dan pembelajaran berkelanjutan.',
    about:
      'Saya bekerja di bidang teknologi, operasional, administrasi, dan dokumentasi—menghadirkan struktur pada pekerjaan kompleks serta mengubah gagasan menjadi hasil yang nyata.',
    artwork: '/profile-hero-941.webp',
  },
  statistics: [
    { value: '4+', label: 'Tahun Pengalaman' },
    { value: '10+', label: 'Proyek' },
    { value: '15+', label: 'Sertifikasi' },
    { value: '∞', label: 'Terus Belajar' },
  ],
  capabilities: [
    { title: 'Pendidikan', description: 'Fondasi yang kokoh untuk terus berkembang.', icon: 'book' },
    { title: 'Pengalaman', description: 'Mengubah pengetahuan menjadi praktik nyata.', icon: 'briefcase' },
    { title: 'Pelatihan', description: 'Peningkatan berkelanjutan untuk menjadi lebih baik.', icon: 'pencil' },
    { title: 'Proyek', description: 'Gagasan yang menjadi solusi nyata.', icon: 'grid' },
    { title: 'Sertifikasi', description: 'Keahlian dan kompetensi yang tervalidasi.', icon: 'award' },
    { title: 'Minat', description: 'Menjelajah melampaui batas, selalu ingin tahu.', icon: 'compass' },
  ],
  education: [
    {
      period: 'Pendidikan Menengah',
      title: 'Sekolah Menengah Kejuruan (SMK)',
      description: 'Fondasi pembelajaran berbasis praktik, kedisiplinan, dan kesiapan kerja.',
    },
    {
      period: 'Pendidikan Tinggi',
      title: 'Sarjana (S1)',
      description: 'Pengembangan cara berpikir analitis, riset, dan pemecahan masalah.',
    },
  ],
  experience: [
    {
      index: '01',
      role: 'Staf Operasional',
      organization: 'Operasional Profesional',
      period: '2020 — 2022',
      description: 'Mendukung operasional harian dan meningkatkan efisiensi alur kerja melalui pelaksanaan yang jelas dan dapat diandalkan.',
      responsibilities: [
        'Menjalankan dan memantau aktivitas operasional harian.',
        'Mencatat perkembangan pekerjaan serta memastikan alur berjalan sesuai kebutuhan.',
        'Mengoordinasikan tindak lanjut pekerjaan dengan pihak terkait.',
        'Membantu mengidentifikasi hambatan dan peluang perbaikan proses.',
      ],
      image: '/work-building.jpg',
      tone: 'charcoal',
    },
    {
      index: '02',
      role: 'Dukungan Administratif',
      organization: 'Administrasi Bisnis',
      period: '2022 — 2024',
      description: 'Menata arsip, mengoordinasikan proses, dan memastikan pekerjaan penting berjalan dengan akurat.',
      responsibilities: [
        'Mengelola dokumen dan arsip agar tersusun serta mudah ditelusuri.',
        'Melakukan pencatatan, pemeriksaan, dan pembaruan data administratif.',
        'Mendukung koordinasi jadwal, kebutuhan dokumen, dan pelaporan rutin.',
        'Menjaga ketelitian serta konsistensi informasi dalam proses kerja.',
      ],
      image: '/work-code.jpg',
      tone: 'paper',
    },
    {
      index: '03',
      role: 'Kontributor Proyek Digital',
      organization: 'Praktik Mandiri',
      period: '2024 — Sekarang',
      description: 'Menghubungkan riset, teknologi, dan dokumentasi untuk menciptakan hasil digital yang bermanfaat.',
      responsibilities: [
        'Mengumpulkan kebutuhan dan menyusun konteks awal proyek digital.',
        'Mendokumentasikan struktur, proses, serta keputusan selama pengerjaan.',
        'Mendukung implementasi, pengujian, dan penyempurnaan hasil.',
        'Menjaga agar solusi tetap jelas, relevan, dan mudah dikembangkan.',
      ],
      image: '/work-laptop.jpg',
      tone: 'crimson',
    },
  ],
  projects: [
    {
      index: '01', slug: 'byd-harmony-auto', title: 'BYD Harmony Auto', category: 'Aplikasi Web', year: '2026', layout: 'wide',
      image: '/work-dashboard.jpg', role: 'Kontributor Pengembangan',
      discipline: 'Teknologi Informasi', artifactType: 'Website / aplikasi web',
      challenge: 'Menyusun pengalaman digital yang tetap jelas ketika informasi, fitur, dan kebutuhan pengguna berkembang bersamaan.',
      approach: 'Mengutamakan arsitektur informasi, alur inti, dan komponen yang konsisten sebelum memperluas fungsi.',
      evidence: { label: 'Lihat website / bukti proyek', href: null as string | null },
      summary: 'Dokumentasi proyek aplikasi web dengan fokus pada struktur informasi, kemudahan penggunaan, dan konsistensi antarmuka.',
      scope: ['Pemetaan kebutuhan dan struktur informasi', 'Perancangan alur serta komponen antarmuka', 'Pengujian tampilan dan penyempurnaan hasil'],
      process: [
        { title: 'Memahami konteks', description: 'Mengurai kebutuhan utama dan menyusun prioritas informasi yang perlu ditampilkan.' },
        { title: 'Menyusun solusi', description: 'Menerjemahkan kebutuhan menjadi struktur halaman dan pola interaksi yang konsisten.' },
        { title: 'Meninjau hasil', description: 'Memeriksa keterbacaan, responsivitas, dan detail visual sebelum penyempurnaan.' },
      ],
      outcome: 'Hasil proyek disusun sebagai fondasi solusi digital yang jelas, mudah dipahami, dan siap dikembangkan lebih lanjut.',
    },
    {
      index: '02', slug: 'arsip-operasional', title: 'Arsip Operasional', category: 'Operasional · Dokumentasi', year: '2025', layout: 'tall',
      image: '/work-mobile.jpg', role: 'Penyusun Sistem Dokumentasi',
      discipline: 'Operasional', artifactType: 'Dokumen & sistem arsip',
      challenge: 'Informasi operasional tersebar dan belum memiliki pola penyimpanan yang mudah dipahami oleh pengguna berikutnya.',
      approach: 'Membentuk klasifikasi, aturan penamaan, dan alur pemeliharaan yang sederhana serta dapat diterapkan bertahap.',
      evidence: { label: 'Lihat bukti sistem arsip', href: null as string | null },
      summary: 'Penyusunan alur dokumentasi untuk membantu informasi operasional tetap rapi, konsisten, dan mudah ditelusuri.',
      scope: ['Inventarisasi kebutuhan dokumen', 'Pengelompokan dan penamaan arsip', 'Penyusunan alur pembaruan informasi'],
      process: [
        { title: 'Inventarisasi', description: 'Mengidentifikasi jenis dokumen, pengguna, dan kebutuhan pencarian informasi.' },
        { title: 'Standardisasi', description: 'Menyusun struktur kategori serta aturan penamaan yang lebih konsisten.' },
        { title: 'Pemeliharaan', description: 'Menyiapkan alur pembaruan agar arsip tetap relevan dan dapat digunakan.' },
      ],
      outcome: 'Struktur arsip menjadi lebih mudah dipahami dan siap dilengkapi dengan dokumentasi implementasi sebenarnya.',
    },
    {
      index: '03', slug: 'sistem-pelaporan', title: 'Sistem Pelaporan', category: 'Data · Administrasi', year: '2025', layout: 'square',
      image: '/work-branding.jpg', role: 'Kontributor Data dan Administrasi',
      discipline: 'Analisis Data', artifactType: 'Spreadsheet & laporan',
      challenge: 'Data perlu dicatat dengan konsisten sekaligus disajikan dalam bentuk yang cepat dipahami untuk pemeriksaan.',
      approach: 'Menetapkan struktur data, aturan validasi, dan hierarki laporan sebelum menyusun visualisasi.',
      evidence: { label: 'Lihat workbook dan laporan', href: null as string | null },
      summary: 'Konsep sistem pelaporan yang mengutamakan ketepatan pencatatan, keterbacaan informasi, dan alur pemeriksaan yang jelas.',
      scope: ['Pemetaan data yang perlu dicatat', 'Penyusunan format dan hierarki laporan', 'Pemeriksaan konsistensi hasil'],
      process: [
        { title: 'Pemetaan data', description: 'Menentukan informasi penting serta hubungan antarbagian dalam laporan.' },
        { title: 'Penyusunan format', description: 'Membentuk struktur yang memudahkan pengisian, pembacaan, dan pemeriksaan.' },
        { title: 'Validasi', description: 'Meninjau konsistensi data dan memperbaiki bagian yang berpotensi menimbulkan ambiguitas.' },
      ],
      outcome: 'Format pelaporan menjadi lebih terstruktur dan dapat dikembangkan sesuai kebutuhan operasional nyata.',
    },
    {
      index: '04', slug: 'catatan-lapangan', title: 'Catatan Lapangan', category: 'Riset · Pekerjaan Profesional', year: '2024', layout: 'wide',
      image: '/work-building.jpg', role: 'Kontributor Riset dan Dokumentasi',
      discipline: 'Riset & Manajemen', artifactType: 'Laporan dan dokumentasi',
      challenge: 'Observasi lapangan yang beragam perlu diterjemahkan menjadi temuan yang dapat ditindaklanjuti.',
      approach: 'Menggabungkan catatan, bukti, dan konteks ke dalam struktur laporan yang memisahkan fakta, analisis, dan tindak lanjut.',
      evidence: { label: 'Lihat laporan dan dokumentasi', href: null as string | null },
      summary: 'Dokumentasi pekerjaan lapangan yang menyatukan observasi, catatan proses, dan temuan menjadi informasi yang lebih terstruktur.',
      scope: ['Pencatatan konteks dan observasi', 'Pengelompokan temuan utama', 'Penyusunan dokumentasi untuk tindak lanjut'],
      process: [
        { title: 'Observasi', description: 'Merekam konteks, aktivitas, dan informasi penting secara sistematis.' },
        { title: 'Sintesis', description: 'Mengelompokkan catatan menjadi tema dan temuan yang lebih mudah dipahami.' },
        { title: 'Dokumentasi', description: 'Menyusun hasil menjadi referensi kerja yang jelas untuk proses berikutnya.' },
      ],
      outcome: 'Catatan lapangan berubah menjadi dokumentasi yang lebih terarah dan mudah digunakan untuk tindak lanjut.',
    },
  ],
  certifications: [
    {
      name: 'Sertifikasi Dukungan TI', issuer: 'Instansi penerbit akan ditambahkan', year: '2025', category: 'Teknologi', image: null,
      description: 'Validasi pembelajaran dan kompetensi pada bidang dukungan teknologi informasi.',
      topics: ['Dasar perangkat keras dan sistem operasi', 'Pemecahan masalah teknis', 'Jaringan dan keamanan dasar', 'Layanan serta komunikasi pengguna'],
    },
    {
      name: 'Sertifikasi Peretasan Etis', issuer: 'Instansi penerbit akan ditambahkan', year: '2025', category: 'Keamanan', image: null,
      description: 'Dokumentasi pembelajaran mengenai prinsip keamanan sistem dan pengujian yang bertanggung jawab.',
      topics: ['Prinsip keamanan informasi', 'Pemetaan kerentanan', 'Pengujian keamanan yang etis', 'Dokumentasi temuan dan mitigasi'],
    },
    {
      name: 'Sertifikasi Ahli Microsoft Excel', issuer: 'Instansi penerbit akan ditambahkan', year: '2024', category: 'Produktivitas', image: null,
      description: 'Validasi keterampilan pengolahan data dan penggunaan perangkat produktivitas.',
      topics: ['Pengelolaan data terstruktur', 'Formula dan fungsi', 'Visualisasi serta pelaporan', 'Pemeriksaan konsistensi data'],
    },
    {
      name: 'Sertifikat Lainnya', issuer: 'Arsip Pembelajaran', year: 'Berkelanjutan', category: 'Pengembangan', image: null,
      description: 'Kumpulan sertifikat pelatihan dan pembelajaran tambahan yang akan dilengkapi secara bertahap.',
      topics: ['Materi pelatihan akan ditambahkan', 'Kompetensi yang diujikan akan ditambahkan'],
    },
  ],
  articles: [
    {
      slug: 'dokumentasi-kerja-yang-dapat-dipakai-kembali',
      title: 'Dokumentasi Kerja yang Dapat Dipakai Kembali',
      category: 'Produktivitas',
      publishedAt: '11 September 2026',
      readTime: '5 menit baca',
      excerpt: 'Dokumentasi yang baik bukan sekadar arsip. Ia membantu orang memahami konteks, mengambil keputusan, dan melanjutkan pekerjaan dengan lebih percaya diri.',
      lead: 'Dokumentasi menjadi bernilai ketika seseorang yang tidak mengikuti proses sejak awal tetap dapat memahami apa yang terjadi, mengapa keputusan dibuat, dan apa yang perlu dilakukan berikutnya.',
      takeaways: ['Tentukan pembaca dan keputusan yang perlu mereka ambil.', 'Gunakan struktur yang konsisten dan mudah diperbarui.', 'Jadikan dokumentasi bagian dari proses kerja sehari-hari.'],
      quote: 'Catatan yang baik tidak berhenti pada informasi; ia membantu orang memahami dan mengambil langkah berikutnya.',
      closingHeading: 'Merangkum gagasan menjadi tindakan.',
      closing: 'Dokumentasi yang matang tidak diukur dari panjangnya, tetapi dari seberapa mudah informasi itu ditemukan, dipahami, dan digunakan kembali oleh orang berikutnya.',
      sections: [
        { heading: 'Mulai dari kebutuhan pembaca', paragraphs: ['Sebelum menulis, tentukan siapa yang akan menggunakan dokumen dan keputusan apa yang perlu mereka ambil. Informasi untuk pelaksana operasional tentu berbeda dengan ringkasan yang dibutuhkan pengambil keputusan.', 'Dengan tujuan yang jelas, dokumentasi dapat tetap ringkas tanpa kehilangan konteks penting.'] },
        { heading: 'Susun struktur yang konsisten', paragraphs: ['Gunakan pola yang dapat diulang: konteks, tujuan, langkah kerja, hasil, hambatan, dan tindak lanjut. Struktur yang konsisten mengurangi waktu pencarian serta memudahkan pembaruan.', 'Nama file, status versi, dan pemilik informasi juga perlu ditulis secara eksplisit agar dokumen tidak berubah menjadi arsip tanpa arah.'] },
        { heading: 'Jadikan dokumentasi bagian dari proses', paragraphs: ['Dokumentasi sebaiknya diperbarui ketika pekerjaan berlangsung, bukan menunggu semuanya selesai. Catatan kecil yang teratur biasanya lebih akurat daripada rekonstruksi panjang di akhir proyek.', 'Tujuan akhirnya bukan menghasilkan lebih banyak dokumen, melainkan menciptakan sumber informasi yang benar-benar dapat digunakan kembali.'] },
      ],
    },
    {
      slug: 'dari-masalah-operasional-ke-solusi-digital',
      title: 'Dari Masalah Operasional ke Solusi Digital',
      category: 'Teknologi',
      publishedAt: '11 September 2026',
      readTime: '6 menit baca',
      excerpt: 'Solusi digital yang baik dimulai dari pemahaman proses kerja—bukan dari memilih teknologi yang paling baru.',
      lead: 'Digitalisasi paling berguna ketika ia menyederhanakan pekerjaan nyata. Karena itu, langkah pertama selalu memahami proses, hambatan, dan orang yang menjalankannya.',
      takeaways: ['Pahami proses sebelum menentukan teknologi.', 'Prioritaskan alur inti dan kemudahan adopsi.', 'Ukur perubahan yang benar-benar dirasakan pengguna.'],
      quote: 'Teknologi menjadi berarti ketika ia mengurangi hambatan dalam pekerjaan nyata.',
      closingHeading: 'Menjadikan solusi lebih relevan.',
      closing: 'Solusi digital yang profesional bukan yang memiliki fitur paling banyak, melainkan yang mengurangi hambatan dan membuat pekerjaan penting menjadi lebih jelas.',
      sections: [
        { heading: 'Petakan proses sebelum membuat fitur', paragraphs: ['Amati bagaimana pekerjaan dilakukan saat ini, informasi apa yang berpindah, serta bagian mana yang sering menimbulkan keterlambatan atau kesalahan. Peta proses memberi gambaran yang lebih jujur daripada daftar fitur.', 'Dari sana, kebutuhan dapat dipisahkan menjadi kebutuhan utama, pendukung, dan hal yang sebenarnya belum perlu dibangun.'] },
        { heading: 'Prioritaskan kejelasan dan adopsi', paragraphs: ['Sistem tidak akan membantu jika pengguna kesulitan memahami alurnya. Bahasa yang familiar, hierarki informasi yang jelas, dan umpan balik yang tepat sering lebih penting daripada banyaknya fungsi.', 'Mulailah dari alur inti yang kecil, uji bersama pengguna, lalu perbaiki berdasarkan hambatan yang benar-benar muncul.'] },
        { heading: 'Ukur perubahan yang relevan', paragraphs: ['Keberhasilan tidak selalu berupa angka besar. Waktu pencarian yang lebih singkat, pencatatan yang lebih konsisten, dan berkurangnya pertanyaan berulang adalah tanda perbaikan yang nyata.', 'Ukuran tersebut membantu tim menentukan apakah solusi perlu diperluas, disederhanakan, atau justru dihentikan.'] },
      ],
    },
    {
      slug: 'membuat-informasi-tetap-jelas-di-antarmuka',
      title: 'Membuat Informasi Tetap Jelas di Antarmuka',
      category: 'Desain Sistem',
      publishedAt: '11 September 2026',
      readTime: '4 menit baca',
      excerpt: 'Antarmuka profesional tidak harus ramai. Kejelasan lahir dari prioritas visual, ritme, dan keputusan yang konsisten.',
      lead: 'Desain antarmuka yang matang membantu pengguna melihat hal terpenting terlebih dahulu, memahami hubungan antarbagian, dan bergerak tanpa banyak menebak.',
      takeaways: ['Bangun hierarki yang mudah dipindai.', 'Gunakan ruang untuk memisahkan konteks.', 'Berikan fungsi yang konsisten pada warna aksen.'],
      quote: 'Kejelasan bukan kekosongan; ia adalah hasil dari prioritas yang tepat.',
      closingHeading: 'Menyatukan keputusan visual.',
      closing: 'Kejelasan visual adalah hasil dari keputusan kecil yang konsisten. Ketika hierarki, ruang, dan warna bekerja sebagai satu sistem, antarmuka terasa lebih tenang dan dapat dipercaya.',
      sections: [
        { heading: 'Bentuk hierarki yang dapat dipindai', paragraphs: ['Perbedaan ukuran, bobot, warna, dan jarak perlu menunjukkan tingkatan informasi. Jika semua elemen sama kuatnya, pengguna harus bekerja lebih keras untuk menemukan titik masuk.', 'Gunakan penekanan hanya pada informasi dan tindakan yang benar-benar membutuhkan perhatian.'] },
        { heading: 'Biarkan ruang bekerja', paragraphs: ['Ruang kosong bukan area yang gagal diisi. Ia memisahkan kelompok informasi, menciptakan ritme, dan membantu elemen penting memperoleh fokus.', 'Konsistensi jarak juga membuat halaman terasa tenang dan profesional, terutama ketika kontennya padat.'] },
        { heading: 'Gunakan warna sebagai sistem', paragraphs: ['Warna aksen sebaiknya memiliki tugas yang jelas: menandai status aktif, tindakan penting, atau detail yang perlu diingat. Penggunaan yang konsisten membuat warna dapat dipahami, bukan hanya dilihat.', 'Palet yang terbatas juga membantu foto, tipografi, dan isi tulisan tampil lebih meyakinkan.'] },
      ],
    },
  ],
  socials: [
    { label: 'LinkedIn', icon: 'linkedin', customIcon: '', href: null as string | null },
    { label: 'Surel', icon: 'email', customIcon: '', href: null as string | null },
    { label: 'GitHub', icon: 'github', customIcon: '', href: null as string | null },
    { label: 'Instagram', icon: 'instagram', customIcon: '', href: null as string | null },
    { label: 'WhatsApp', icon: 'whatsapp', customIcon: '', href: null as string | null },
  ],
} as const;
